/**
	Generated by sails-inverse-model
	Date:Thu Jan 21 2021 12:03:07 GMT-0600 (GMT-06:00)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            autoIncrement: true
        },
        nombre: {
            type: "string",
            columnType: "varchar",
            maxLength: 50,
            required: true
        }
    }
};